let countingDown = 5;
let remainingSeconds = 0;

//terms to type 
const term=[
'Abs',
'Absolute Strength',
'Active rest',
'Aerobic exercise',
'Aerobics',
'Agonist muscles',
'Antagonist muscle',
'Anterior chain',
'Back-cycling',
'Barbell',
'Bench press',
'Biceps',
'Bicep curls',
'Bleep test',
'Bodyweight exercises',
'cardiovascular conditioning',
'Bulking',
'Burpees',
'Cardio',
'Chest fly',
'Chest press',
'Chin up',
'Circuit training',
'Core',
'Crunch',
'Deadlift',
'Deltoid muscles',
'Dumbbell',
'Endurance training',
'Exercise ball',
'Exercise wheel',
'Fat burn',
'Hamstrings',
'Insanity',
'Kegel exercises',
'Kettlebell',
'Lat pull downs',
'Puss ups',
]

